config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  get 'home/about'
  root "home#index"
  # root "friends#index"
  resources :home
  resources :friends
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]


  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    # @friend = Friend.new
    @friend=current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    # @friend = Friend.new(friend_params)
    @friend=current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend=current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not Authorized to edit this friend" if @friend.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
    @about_me="My name is Srinivas Rao and here are my friends.
               To see my friends click on Friends."
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="m-4 field form-group">
    <%= form.text_field :first_name, class:"form-control", placeholder:"First Name" %>
  </div>

  <div class="m-4 field form-group">
    <%= form.text_field :last_name, class:"form-control", placeholder:"Last Name" %>
  </div>

  <div class="m-4 field form-group">
    <%= form.text_field :email, class:"form-control", placeholder:"Email" %>
  </div>
  
  <div class="m-4 field form-group">
    <%= form.text_field :phone, class:"form-control", placeholder:"Phone" %>
  </div>

  <div class="m-4 field form-group">
    <%= form.text_field :twitter, class:"form-control", placeholder:"Twitter" %>
  </div>

  <div class="m-4 field form-group">
    <%= form.number_field :user_id, id: :friend_user_id, class:"form-control", placeholder:"User id", value:current_user.id, type: :hidden %>
  </div>

  <div class="m-4 actions"> 
    <%= form.submit class:"btn btn-outline-dark" %>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<div class="m-4 p-5"style ="background-color: #bec3c4">
  <h1><%= @friend.first_name %> <%= @friend.last_name %></h1>
  <p> <%= @friend.email %> |
      <%= @friend.phone %> |
      <%= @friend.twitter %> </p>
      <br><br>
  <%= link_to "Edit", edit_friend_path(@friend), class:"btn btn-outline-dark" %> |
  <%= link_to "Back", friends_path, class:"btn btn-outline-dark" %> |
  <%= link_to "Destroy", @friend, method: :delete, class:"btn  btn-outline-dark" %>

</div>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show", @friend, class:"btn btn-outline-dark" %> |
  <%= link_to "Back", friends_path, class: "btn btn-outline-dark" %>
</div>

app/views/friends/index.html.erb
    <%= stylesheet_link_tag "custom", "data-turbo-track": "reload" %>


<% if user_signed_in? %>
<center><h1>Friends lists</h1></center>
<div class="m-4 cd" >
<table class="table table-bordered table-striped table-hover">
  <thead class="thead-dark">
    <tr>
      <th>Name</th>
      <!-- <th>Last Name</th> -->
      <th>Email</th>
      <th>Phone NO</th>
      <th>Twitter</th>
      <th>User Id</th>
    </tr>
  </thead>

  <tbody>
    <% @friends.each do |friend| %>
    <% if friend.user==current_user%>
    <tr>
      <td>
        <%= friend.first_name %>
        <%= friend.last_name %>
      </td>
      <td><%= friend.email %></td>
      <td><%= friend.phone %></td>
      <td><%= friend.twitter %></td>
      <td><%= friend.user_id %></td>
      <th><%= link_to "Show", friend, class:"btn btn-dark" %></th>
      <th><%= link_to "Edit", edit_friend_path(friend), class:"btn btn-dark" %></th>
      <th><%= link_to "Destroy", friend_path(friend), class:"btn btn-dark", data: {turbo_method: :Delete, 
        turbo_confirm: :"Are you sure"} %></th>
        </tr>
    <% end %>
    <% end %>
  </tbody>
</table>
</div>
<div class="m-4">
<%= link_to "New friend", new_friend_path, class: "btn btn-dark" %>
</div>

<% else %>
<%= render 'home/index  '%>
<% end %>

app/views/friends/new.html.erb
<center><h1>New friend</h1></center>

<%= render "form", friend: @friend %> 

<div class="m-4">
  <%= link_to "Back", friends_path, class:"btn btn-info" %>
</div>

app/views/friends/show.html.erb
<%= render @friend %>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Friend App', root_path, class: "navbar-brand" %>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
        <li class="nav-item">
          <%= link_to "About", home_about_path, class:'nav-link' %>
        </li>

         <li class="nav-item">
          <%= link_to "Friends", friends_path, class:'nav-link' %>
        </li>
        <% if user_signed_in? %>
         <li class="nav-item">
          <%= link_to "Sign Out", destroy_user_session_path, data: {turbo_method: :delete,
            turbo_confirm: :"Are you sure you want to log_out!!"}, class:'nav-link' %>
        </li>

         <li class="nav-item">
          <%= link_to "New Friend", new_friend_path, class:'nav-link' %>
        </li>

         <li class="nav-item">
          <%= link_to "Edit Profile", edit_user_registration_path, class:'nav-link' %>
        </li>

        <% else %>
         <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class:'nav-link' %>
        </li>

         <li class="nav-item">
          <%= link_to "Sign In", new_user_session_path, class:'nav-link' %>
        </li>


        <!-- <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li> -->
       <% end %> 
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About us..</h1>

<h3><%= @about_me %></h3>

app/views/home/index.html.erb
 <%= stylesheet_link_tag "custom", "data-turbo-track": "reload" %>

<div class="dd">
		<h1>Home#index</h1>
		<p>Find me in app/views/home/index.html.erb sdhbsjhbhbsdjhjhcv</p>
</div>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>

  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>friends</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <%= render "home/header" %>

    <% if notice %>
      <%= render "layouts/alerts" %>
    <% end %>
    
    <%= yield %>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>